### ISSUE TITLE
When the Allocation Quota Attribute value is set to 0 it fails.

### ISSUE THREAD

**Issue by Milstein** [nerc-project/coldfront-plugin-cloud#141]
- When the Allocation Quota Attribute i.e. **OpenStack Volume GB Quota** and **OpenStack Swift Quota in Gigabytes** for **NERC (OpenStack)** resource type allocation is set to Zero(0) it fails.
- **Error:**
```
'x-account-meta-quota-bytes' : Traceback (most recent call last):
File "/opt/venv/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_cloud/tasks.py", line 109, in activate_allocation
allocator.set_quota(project_id)
File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_cloud/openstack.py", line 179, in set_quota
self._set_object_quota(project_id, payload)
File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_cloud/openstack.py", line 186, in _set_object_quota
payload[QUOTA_KEY_MAPPING['object']['keys'][
KeyError: 'x-account-meta-quota-bytes'
```
- Need to verify if any other quota attributes set to 0 is not raising this issue.
- Need to fix for **NERC-OCP (OpenShift)** resource type allocation attributes as well.

**Comment by Milstein** [comment]
Can be verified by testing:
for volume storage `openstack quota show`  and for the Swift Quota `openstack object store account show`
