### ISSUE TITLE
validate_allocations fails on project id not existing

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#60]
```1000730000@coldfront-deployment-786dc494f-trzxm:/$ coldfront validate_allocations
Traceback (most recent call last):
  File "/opt/venv/bin/coldfront", line 33, in <module>
    sys.exit(load_entry_point('coldfront==1.0.4', 'console_scripts', 'coldfront')())
  File "/opt/venv/lib/python3.9/site-packages/coldfront/__init__.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_openstack/management/commands/validate_allocations.py", line 44, in handle
    quota = allocator.get_quota(
  File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_openstack/openstack.py", line 163, in get_quota
    compute_quota = self.compute.quotas.get(project_id)
  File "/opt/venv/lib/python3.9/site-packages/novaclient/v2/quotas.py", line 40, in get
    return self._get(url % params, "quota_set")
  File "/opt/venv/lib/python3.9/site-packages/novaclient/base.py", line 352, in _get
    resp, body = self.api.client.get(url)
  File "/opt/venv/lib/python3.9/site-packages/keystoneauth1/adapter.py", line 395, in get
    return self.request(url, 'GET', **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/novaclient/client.py", line 78, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.BadRequest: Project ID 0a43fb479e31496abbe7d43fbca19c84 is not a valid project. (HTTP 400) (Request-ID: req-e6e2d7f5-ca6d-4642-bc28-7b4c9ca22c68)
```

**Comment by Milstein** [comment]
```
$ openstack quota show 0a43fb479e31496abbe7d43fbca19c84
No project with a name or ID of '0a43fb479e31496abbe7d43fbca19c84' exists.
```
