### ISSUE TITLE
Create management command to update EULA from URL

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#68]
As an administrator, I want the terms of service that my users have to accept to be up to date and fetched from a central location where they are stored in plaintext format.

Create a new attribute on the resource called `eula_url` and create a new management command that fetches the contents of that location and updates the `eula` attribute on the resource.

**Comment by naved001** [comment]
Hi @knikolla here's a draft of what I have:

https://github.com/naved001/coldfront-plugin-cloud/blob/add-update-eula-command/src/coldfront_plugin_cloud/management/commands/update_eula.py

Though at this point it needs to know the resource name and resource type it's updating the eula for (instead of going over all resources).

**Comment by knikolla** [comment]
Hey Naved, look pretty good. Some minor feedback

1. Is the resource_type argument really required? I think just name should be enough. 
2. Please check the status of the http request and return an error if it doesn't fetch correctly.
3. There's a `get_or_create` method that would merge your try/catch block https://github.com/nerc-project/coldfront-plugin-cloud/blob/6978fc68f3356ff74400419e06883cd9a64801d5/src/coldfront_plugin_cloud/management/commands/add_openshift_resource.py#L40

**Comment by naved001** [comment]
> Is the resource_type argument really required? I think just name should be enough.

I guess not if I can get the resource object just by name. 

> There's a get_or_create method that would merge your try/catch block 

I tried that and the similar `update_or_create` method, but on a subsequent run I was getting SQL Integrity error and I couldn't actually update it. I will post the full error message later.

**Comment by naved001** [comment]
Here's the full error when I use get_or_create (or update_or_create). The error only shows up when it actually has to update the value i.e. if I re-run the command with the same url then nothing happens.

```
Traceback (most recent call last):
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
coldfront.core.resource.models.DoesNotExist: ResourceAttribute matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: resource_resourceattribute.resource_attribute_type_id, resource_resourceattribute.resource_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/coldfront_venv/bin/coldfront", line 8, in <module>
    sys.exit(manage())
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/coldfront/__init__.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/coldfront-plugin-cloud/src/coldfront_plugin_cloud/management/commands/update_eula.py", line 38, in handle
    ResourceAttribute.objects.update_or_create(
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/model_utils/models.py", line 38, in save
    super().save(*args, **kwargs)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tmp/coldfront_venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: resource_resourceattribute.resource_attribute_type_id, resource_resourceattribute.resource_id
```
